#! /bin/sh
# yes I know this is a hack, but I did it in vi in 3 sec.
#
fproto builtin.c >builtin.pro
fproto cond.c >cond.pro
fproto exec.c >exec.pro
fproto glob.c >glob.pro
fproto hist.c >hist.pro
fproto init.c >init.pro
fproto jobs.c >jobs.pro
fproto lex.c >lex.pro
fproto loop.c >loop.pro
fproto math.c >math.pro
fproto mem.c >mem.pro
fproto params.c >params.pro
fproto subst.c >subst.pro
fproto table.c >table.pro
fproto text.c >text.pro
fproto utils.c >utils.pro
fproto watch.c >watch.pro
fproto zle_bindings.c >zle_bindings.pro
fproto zle_emacs.c >zle_emacs.pro
fproto zle_main.c >zle_main.pro
fproto zle_refresh.c >zle_refresh.pro
fproto zle_tricky.c >zle_tricky.pro
fproto zle_utils.c >zle_utils.pro
fproto zle_vi.c >zle_vi.pro
fproto parse.y >parse.pro
